repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.3 
  hooks:
    - id: terraform_fmt
      args:
        - --args=-diff
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=false
    - id: terraform_tflint
      args:
        - --args=--enable-rule=terraform_documented_variables
        - --args=--enable-rule=terraform_unused_required_providers
        - --args=--enable-rule=terraform_unused_declarations
        - --args=--enable-rule=terraform_typed_variables
        - --args=--enable-rule=terraform_standard_module_structure
        - --args=--enable-rule=terraform_naming_convention
        - --args=--enable-rule=terraform_comment_syntax
